version: 2
updates:
  - package-ecosystem: 'npm'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    directory: '/'
    open-pull-requests-limit: 50
    schedule:
      interval: 'daily'
    versioning-strategy: 'increase'
