restore_cache: &restore_cache
  keys:
    - node-modules-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{
      checksum "package.json" }}
    - node-modules-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum
      "package.json" }}

save_cache: &save_cache
  key:
    node-modules-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{
    checksum "package.json" }}
  paths:
    - node_modules

docker: &docker
  - image: 'node:18'

steps: &steps
  - checkout
  - restore_cache: *restore_cache
  - run: npm install
  - run: npm run build
  - run: npm test
  - save_cache: *save_cache
  - store_test_results:
      path: reports
  - store_artifacts:
      path: reports

version: 2

jobs:
  lint:
    docker: *docker
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: npm install
      - run: npm run lint
      - save_cache: *save_cache

  test-node-16:
    docker:
      - image: node:18
    steps: *steps

  test-node-18:
    docker:
      - image: node:18
    steps: *steps

  release:
    docker:
      - image: node:18
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: npm install
      - deploy:
          command: |
            echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ./.npmrc
            npm whoami
            npm run semantic-release
      - save_cache: *save_cache

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test-node-16
      - test-node-18
      - release:
          context: semantic-release
          filters:
            branches:
              only: master
          requires:
            - test-node-16
            - test-node-18
            - lint
